# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x03stt\"h\n\x10RecognizeRequest\x12&\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x14.stt.StreamingConfigH\x00\x12\x17\n\raudio_content\x18\x02 \x01(\x0cH\x00\x42\x13\n\x11streaming_request\"^\n\x0fStreamingConfig\x12\x10\n\x08strategy\x18\x01 \x01(\t\x12\x12\n\nmodel_path\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\x10\n\x08language\x18\x04 \x01(\t\"g\n\x11RecognizeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t2U\n\nSttService\x12G\n\x12StreamingRecognize\x12\x15.stt.RecognizeRequest\x1a\x16.stt.RecognizeResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNIZEREQUEST']._serialized_start=18
  _globals['_RECOGNIZEREQUEST']._serialized_end=122
  _globals['_STREAMINGCONFIG']._serialized_start=124
  _globals['_STREAMINGCONFIG']._serialized_end=218
  _globals['_RECOGNIZERESPONSE']._serialized_start=220
  _globals['_RECOGNIZERESPONSE']._serialized_end=323
  _globals['_STTSERVICE']._serialized_start=325
  _globals['_STTSERVICE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
